"""
Generate AI voice samples from multiple TTS engines for better generalization
"""
import os
from pathlib import Path

# Sentences to convert
SENTENCES = [
    "Hello, welcome to our AI voice detection system.",
    "This is an automated message generated by artificial intelligence.",
    "Please listen carefully to the following instructions.",
    "Thank you for your patience while we process your request.",
    "The weather today will be sunny with a high of seventy degrees.",
    "Our customer service team is available twenty four hours a day.",
    "Press one for sales, press two for support, press three for billing.",
    "Your call is important to us, please stay on the line.",
    "This recording may be monitored for quality assurance purposes.",
    "Have a wonderful day and thank you for choosing our service.",
    "The next available representative will assist you shortly.",
    "For more information, please visit our website.",
    "Your order has been confirmed and will ship within two business days.",
    "Please enter your account number followed by the pound sign.",
    "We appreciate your business and look forward to serving you again.",
]

OUTPUT_DIR = Path("data/ai/english")

def generate_gtts_samples():
    """Generate samples using Google TTS"""
    try:
        from gtts import gTTS
        print("Generating gTTS samples...")
        for i, text in enumerate(SENTENCES):
            output_path = OUTPUT_DIR / f"gtts_{i+1}.mp3"
            if not output_path.exists():
                tts = gTTS(text=text, lang='en')
                tts.save(str(output_path))
                print(f"  Created: gtts_{i+1}.mp3")
        print(f"  gTTS: {len(SENTENCES)} samples")
    except ImportError:
        print("  gTTS not installed, skipping...")
    except Exception as e:
        print(f"  gTTS error: {e}")

def generate_pyttsx3_samples():
    """Generate samples using pyttsx3 (offline TTS)"""
    try:
        import pyttsx3
        print("Generating pyttsx3 samples...")
        engine = pyttsx3.init()
        
        # Get available voices
        voices = engine.getProperty('voices')
        
        for vi, voice in enumerate(voices[:3]):  # Use up to 3 voices
            engine.setProperty('voice', voice.id)
            for i, text in enumerate(SENTENCES[:5]):  # 5 sentences per voice
                output_path = OUTPUT_DIR / f"pyttsx3_v{vi}_{i+1}.wav"
                if not output_path.exists():
                    engine.save_to_file(text, str(output_path))
                    print(f"  Created: pyttsx3_v{vi}_{i+1}.wav")
            engine.runAndWait()
        print(f"  pyttsx3: Generated samples")
    except ImportError:
        print("  pyttsx3 not installed, skipping...")
    except Exception as e:
        print(f"  pyttsx3 error: {e}")

def generate_edge_tts_extra_voices():
    """Generate samples using Edge TTS with different voices"""
    try:
        import asyncio
        import edge_tts
        
        # Different Edge TTS voices for variety
        VOICES = [
            "en-US-AriaNeural",
            "en-US-GuyNeural", 
            "en-GB-SoniaNeural",
            "en-GB-RyanNeural",
            "en-AU-NatashaNeural",
            "en-IN-NeerjaNeural",
        ]
        
        async def generate_voice(voice, text, output_path):
            communicate = edge_tts.Communicate(text, voice)
            await communicate.save(str(output_path))
        
        print("Generating Edge TTS extra voice samples...")
        for vi, voice in enumerate(VOICES):
            for i, text in enumerate(SENTENCES[:3]):
                output_path = OUTPUT_DIR / f"edge_extra_{voice.split('-')[1]}_{i+1}.mp3"
                if not output_path.exists():
                    asyncio.run(generate_voice(voice, text, output_path))
                    print(f"  Created: edge_extra_{voice.split('-')[1]}_{i+1}.mp3")
        print(f"  Edge TTS extra voices: Generated")
    except ImportError:
        print("  edge-tts not installed, skipping...")
    except Exception as e:
        print(f"  Edge TTS error: {e}")

if __name__ == "__main__":
    print("=" * 50)
    print("GENERATING DIVERSE AI VOICE SAMPLES")
    print("=" * 50)
    
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    generate_gtts_samples()
    generate_pyttsx3_samples()
    generate_edge_tts_extra_voices()
    
    print("\n" + "=" * 50)
    print("DONE! Now retrain the model with: python train.py")
    print("=" * 50)
